// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrNEIP67mm68JZwGktZbM_XC6XiQzzZDU',
    appId: '1:671770223062:web:8543fcf99ef5ebdd018477',
    messagingSenderId: '671770223062',
    projectId: 'stockmanagement-2f7de',
    authDomain: 'stockmanagement-2f7de.firebaseapp.com',
    storageBucket: 'stockmanagement-2f7de.firebasestorage.app',
    measurementId: 'G-1L3H6QYC24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7b2TiFCfgTmVc40vT5DUE8vOLEvA1Bs',
    appId: '1:671770223062:android:e7dd7ddbd40e8c44018477',
    messagingSenderId: '671770223062',
    projectId: 'stockmanagement-2f7de',
    storageBucket: 'stockmanagement-2f7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcmazPiiDLy0m0UAO0AP0xcuwBA_rrYo',
    appId: '1:671770223062:ios:ea5b176d66405a25018477',
    messagingSenderId: '671770223062',
    projectId: 'stockmanagement-2f7de',
    storageBucket: 'stockmanagement-2f7de.firebasestorage.app',
    iosBundleId: 'com.example.stockManagementApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPcmazPiiDLy0m0UAO0AP0xcuwBA_rrYo',
    appId: '1:671770223062:ios:ea5b176d66405a25018477',
    messagingSenderId: '671770223062',
    projectId: 'stockmanagement-2f7de',
    storageBucket: 'stockmanagement-2f7de.firebasestorage.app',
    iosBundleId: 'com.example.stockManagementApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrNEIP67mm68JZwGktZbM_XC6XiQzzZDU',
    appId: '1:671770223062:web:10eaa9fde74d453a018477',
    messagingSenderId: '671770223062',
    projectId: 'stockmanagement-2f7de',
    authDomain: 'stockmanagement-2f7de.firebaseapp.com',
    storageBucket: 'stockmanagement-2f7de.firebasestorage.app',
    measurementId: 'G-MQ3QPF2RDN',
  );
}
